taskid: FunASR_01
result: test_results/FunASR_01/results.jsonl
output_dir: output/FunASR_01/
groundtruth: groundtruth/FunASR_01/gt.txt
test_script: test_scripts/FunASR_01/test_script.py
multi_output: false
